"""Drive a free Kaggle GPU from the app — dispatch a render, poll it, pull back the MP4.

Real singing (ACE-Step) + real animation (LTX) need an NVIDIA GPU this machine doesn't have, so
the GPU work runs on Kaggle's free hardware. Rather than the user pasting notebook cells, the app
builds a one-off **private** Kaggle *kernel* (a batch script — the ToS-safe way, not a tunnel),
pushes it via the Kaggle API, polls until it finishes, and downloads ``song.mp4``.

This is a thin wrapper over the ``kaggle`` CLI (``pip install kaggle``) so a missing/invalid API
token surfaces as a clear message instead of crashing the app on import (the kaggle SDK
authenticates at import time). Auth = ``~/.kaggle/kaggle.json`` or KAGGLE_USERNAME/KAGGLE_KEY.

Setup the user does ONCE: kaggle.com -> Settings -> API -> "Create New Token" -> save the
downloaded ``kaggle.json`` to ``~/.kaggle/kaggle.json`` (and phone-verify the account for GPU).
"""
from __future__ import annotations

import importlib.util
import json
import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from .config import settings

_KERNEL_TITLE = "toonforge-render"


@dataclass
class KaggleStatus:
    state: str            # queued | running | complete | error | unknown
    message: str = ""

    @property
    def done(self) -> bool:
        return self.state in ("complete", "error", "cancelacknowledged")

    @property
    def ok(self) -> bool:
        return self.state == "complete"


def _kaggle_cmd() -> list[str] | None:
    """Command prefix to invoke the Kaggle CLI. Prefer the PATH exe, else `python -m kaggle`
    on the app's own interpreter — the `kaggle.exe` script often lands in a dir that's not on
    PATH, so module invocation is the reliable path as long as the package is importable here."""
    exe = shutil.which("kaggle")
    if exe:
        return [exe]
    if importlib.util.find_spec("kaggle") is not None:
        return [sys.executable, "-m", "kaggle"]
    return None


def _credentials() -> tuple[str, str] | None:
    """(username, key) from env or ~/.kaggle/kaggle.json, else None."""
    user, key = os.environ.get("KAGGLE_USERNAME"), os.environ.get("KAGGLE_KEY")
    if user and key:
        return user, key
    cfg = Path(os.environ.get("KAGGLE_CONFIG_DIR", str(Path.home() / ".kaggle"))) / "kaggle.json"
    try:
        data = json.loads(cfg.read_text())
        if data.get("username") and data.get("key"):
            return data["username"], data["key"]
    except Exception:  # noqa: BLE001 — missing/garbled file: treat as no creds
        pass
    return None


def availability() -> tuple[bool, str]:
    """(usable, hint). Checks the CLI is installed and credentials are present."""
    if _kaggle_cmd() is None:
        return False, "Kaggle CLI not installed in the backend env. Run: pip install kaggle"
    if _credentials() is None:
        return False, ("No Kaggle API token. At kaggle.com -> Settings -> API -> Create New "
                       "Token, then save kaggle.json to ~/.kaggle/kaggle.json (or set "
                       "KAGGLE_USERNAME / KAGGLE_KEY).")
    return True, "ready"


def kernel_slug() -> str:
    """<username>/toonforge-render — one reusable kernel; each dispatch is a new version/run."""
    if settings.kaggle_kernel_slug:
        return settings.kaggle_kernel_slug
    creds = _credentials()
    user = (creds[0] if creds else "") or os.environ.get("KAGGLE_USERNAME", "user")
    return f"{user}/{_KERNEL_TITLE}"


def _run(args: list[str], timeout: float = 180.0) -> subprocess.CompletedProcess:
    cmd = _kaggle_cmd()
    if cmd is None:
        raise RuntimeError("Kaggle CLI not installed (pip install kaggle).")
    return subprocess.run([*cmd, *args], capture_output=True, text=True, timeout=timeout)


def _render_kernel_source(prompt: str, style: str, scenes: int, lyrics: str = "") -> str:
    """The batch script Kaggle runs on its GPU. Keys are injected from settings; the kernel is
    PRIVATE, so they're visible only to the account owner (the user's own keys). gpu_render.py
    carries all the T4 fixes (conv-fp32 shim, song-in-subprocess, LTX caps). When LYRICS is set,
    the render keeps the user's exact words and casts characters/scenes from them."""
    repo = settings.kaggle_render_repo
    return f"""# Auto-generated by ToonForge. Runs the GPU render on Kaggle, writes /kaggle/working/song.mp4.
import os, sys, subprocess

REPO   = {repo!r}
PROMPT = {prompt!r}
STYLE  = {style!r}
SCENES = {str(int(scenes))!r}
LYRICS = {lyrics!r}

os.chdir("/kaggle/working")
subprocess.run(["rm", "-rf", "Video_Generator"], check=False)
subprocess.run(["git", "clone", "--depth", "1", REPO, "Video_Generator"], check=True)
os.chdir("/kaggle/working/Video_Generator/backend")

pip = [sys.executable, "-m", "pip", "install", "-q"]
subprocess.run(pip + ["-r", "requirements.txt"], check=True)
subprocess.run(pip + ["diffusers>=0.32", "transformers>=4.44", "accelerate",
                      "sentencepiece", "imageio[ffmpeg]"], check=True)
subprocess.run(pip + ["git+https://github.com/ace-step/ACE-Step.git"], check=True)

env = dict(os.environ)
env["OPENROUTER_API_KEY"]    = {settings.openrouter_api_key!r}
env["CLOUDFLARE_ACCOUNT_ID"] = {settings.cloudflare_account_id!r}
env["CLOUDFLARE_API_TOKEN"]  = {settings.cloudflare_api_token!r}
env["PROVIDER_IMAGE"] = "cloudflare"
env["PROVIDER_VIDEO"] = "ltx_local"
env["PROVIDER_SVS"]   = "acestep_local"
env["PROVIDER_LLM"]   = "openrouter"
env["GPU_OFFLOAD"]    = "1"
env["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"

args = [sys.executable, "scripts/gpu_render.py", "--style", STYLE, "--out", "/kaggle/working/song.mp4"]
if LYRICS.strip():
    open("/kaggle/working/lyrics.txt", "w", encoding="utf-8").write(LYRICS)
    args += ["--lyrics-file", "/kaggle/working/lyrics.txt"]
else:
    args += ["--prompt", PROMPT, "--scenes", SCENES]
r = subprocess.run(args, env=env)
if r.returncode != 0 or not os.path.exists("/kaggle/working/song.mp4"):
    raise SystemExit("render failed")
print("RENDER_OK")
"""


def _write_kernel_dir(dirpath: Path, prompt: str, style: str, scenes: int, lyrics: str = "") -> None:
    (dirpath / "render_kernel.py").write_text(
        _render_kernel_source(prompt, style, scenes, lyrics), encoding="utf-8")
    meta = {
        "id": kernel_slug(),
        "title": _KERNEL_TITLE,
        "code_file": "render_kernel.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": True,
        "enable_gpu": True,
        "enable_internet": True,
        "dataset_sources": [],
        "competition_sources": [],
        "kernel_sources": [],
    }
    (dirpath / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")


def dispatch(prompt: str, style: str, scenes: int, lyrics: str = "") -> str:
    """Push the render kernel (queues a fresh run on Kaggle's GPU). Returns the kernel slug.
    If lyrics is given, the render keeps the user's words and casts characters/scenes from them."""
    ok, hint = availability()
    if not ok:
        raise RuntimeError(hint)
    with tempfile.TemporaryDirectory() as tmp:
        d = Path(tmp)
        _write_kernel_dir(d, prompt, style, scenes, lyrics)
        proc = _run(["kernels", "push", "-p", str(d)])
    if proc.returncode != 0:
        raise RuntimeError(f"kaggle kernels push failed: {(proc.stderr or proc.stdout).strip()[:500]}")
    return kernel_slug()


def status(slug: str | None = None) -> KaggleStatus:
    """Latest run state of the kernel."""
    proc = _run(["kernels", "status", slug or kernel_slug()], timeout=60)
    out = (proc.stdout + proc.stderr).lower()
    for state in ("complete", "error", "cancelacknowledged", "running", "queued"):
        if state in out:
            return KaggleStatus(state, proc.stdout.strip())
    return KaggleStatus("unknown", proc.stdout.strip() or proc.stderr.strip())


def fetch_output(dest_dir: Path, slug: str | None = None) -> Path | None:
    """Download the kernel's /kaggle/working output; return the path to song.mp4 if present."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    proc = _run(["kernels", "output", slug or kernel_slug(), "-p", str(dest_dir)], timeout=300)
    if proc.returncode != 0:
        raise RuntimeError(f"kaggle kernels output failed: {(proc.stderr or proc.stdout).strip()[:500]}")
    mp4 = dest_dir / "song.mp4"
    return mp4 if mp4.exists() else None
